### PR TITLE
Fix the issue when the FlutterViewController is not the rootViewController

### PR DESCRIPTION
**Pull request by uc-nfdz**
PR from: https://github.com/Usercentrics/flutter-sdk/pull/26

### CODE REVIEW

**Comment by uc-nfdz** [comment]
@mohammadshrahi what do you think about this fix?

**Comment by mohammadshrahi** [comment]
> @mohammadshrahi what do you think about this fix?

I think this implementation should work fine, I will give it a shot and let you know.

**Comment by uc-nfdz** [comment]
Any update @mohammadshrahi ?

**Comment by mohammadshrahi** [comment]
> Any update @mohammadshrahi ?

It's working fine, thanks for the fast replay.

**Comment by uc-nfdz** [comment]
Thank you for your help and contribution.

**Pull request merged**
